# Generated by Django 5.1 on 2024-12-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0005_remove_ingredients_product_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "recipecategories",
            },
        ),
        migrations.CreateModel(
            name="Dishes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=300)),
                ("dish_description", models.CharField(max_length=500)),
                (
                    "subcategory",
                    models.CharField(
                        choices=[("hot", "Hot"), ("cold", "Cold"), ("other", "Other")],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "dish_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "RRP",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dishes.dishcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["dish_name"],
            },
        ),
        migrations.CreateModel(
            name="DishElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=16, null=True
                    ),
                ),
                (
                    "dish_element",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="element",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.dishes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DishSauce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sauce_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=16, null=True
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.dishes"
                    ),
                ),
                (
                    "dish_sauce",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sauce",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DishSides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=16, null=True
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dishes.dishes"
                    ),
                ),
                (
                    "dish_side",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sides",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
