# Generated by Django 5.1 on 2024-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="ingredient_cost",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=16, null=True
            ),
        ),
    ]
