# Generated by Django 5.1 on 2024-11-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_ingredients_ingredient_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["recipe_name"]},
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe",
            new_name="recipe_name",
        ),
    ]
