# Generated by Django 5.1 on 2024-11-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredients",
            name="product_cost",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=16, null=True
            ),
        ),
    ]
