# Generated by Django 5.1 on 2024-11-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_ingredients_product_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredients",
            name="product_cost",
        ),
    ]
