# Generated by Django 5.1 on 2024-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("grams", "g"), ("quantity", "qty"), ("ml", "ml")],
                max_length=10,
            ),
        ),
    ]
