# Generated by Django 5.1 on 2024-08-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("g", "g"), ("qty", "qty"), ("ml", "ml")], max_length=10
            ),
        ),
    ]
