# Generated by Django 5.1 on 2024-11-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_product_cost_alter_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_cost",
        ),
    ]
